### ISSUE TITLE
Suggestion to add folder in .gitignore file

### ISSUE THREAD

**Issue by LidiyaNorman** [datascienceisrael/projectTemplate#3]
Issue and solution:
When we first open a project in R, the packrat is installing packages under the "src" folder.
We need to ignore this folder in the .gitignore file because this folder will be created by packrat for each user and there is no need to update it to GITHUB.

.gitignore, current version:
packrat/lib*/

.gitignore, after the update:
packrat/lib*/
**packrat/src/**

**Comment by ShaulAb** [comment]
**Accepted** - this may cause problems when users use other R versions for example.
Latest commit  should solve it.
